---
dist: bionic
language: python

install:
  - bash scripts/install.sh

env:
  global:
    - UBUNTU_VERSION=18.04
    - BUILD_ID=0

# job templates

pep8: &pep8
  stage: pep8
  script: bash scripts/pep8.sh

base: &base
  stage: base
  script: bash scripts/stage.sh

infrastructure: &infrastructure
  stage: infrastructure
  script: bash scripts/stage.sh

openstack-core: &openstack-core
  stage: openstack-core
  script: bash scripts/stage.sh

openstack-additional: &openstack-additional
  stage: openstack-additional
  script: bash scripts/stage.sh

jobs:
  include:

# base

    - <<: *pep8

    - <<: *base
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = master
      env:
        - OPENSTACK_VERSION: master

    - <<: *base
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = rocky
      env:
        - OPENSTACK_VERSION: rocky

    - <<: *base
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = stein
      env:
        - OPENSTACK_VERSION: stein

    - <<: *base
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = train
      env:
        - OPENSTACK_VERSION: train

# infrastructure

    - <<: *infrastructure
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = master
      env:
        - OPENSTACK_VERSION: master

    - <<: *infrastructure
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = rocky
      env:
        - OPENSTACK_VERSION: rocky

    - <<: *infrastructure
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = stein
      env:
        - OPENSTACK_VERSION: stein

    - <<: *infrastructure
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = train
      env:
        - OPENSTACK_VERSION: train

# openstack-core

    - <<: *openstack-core
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = master
      env:
        - OPENSTACK_VERSION: master

    - <<: *openstack-core
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = rocky
      env:
        - OPENSTACK_VERSION: rocky

    - <<: *openstack-core
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = stein
      env:
        - OPENSTACK_VERSION: stein

    - <<: *openstack-core
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = train
      env:
        - OPENSTACK_VERSION: train

# openstack-additional

    - <<: *openstack-additional
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = master
      env:
        - OPENSTACK_VERSION: master

    - <<: *openstack-additional
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = rocky
      env:
        - OPENSTACK_VERSION: rocky

    - <<: *openstack-additional
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = stein
      env:
        - OPENSTACK_VERSION: stein

    - <<: *openstack-additional
      if: env(TRAVIS_OPENSTACK_VERSION) IS NOT present OR env(TRAVIS_OPENSTACK_VERSION) = train
      env:
        - OPENSTACK_VERSION: train
