---
- secret:
    name: SECRET_CONTAINER_IMAGES_KOLLA
    data:
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - TIgSEYhQn6UuiABEV1t1vWypKyay/8dsvQmIBo1W3fwEZ7PsUpmJDZ3FtDZaYuJlukZpg
          uvlII0RHl8DouDblLqmIDNSOKUAAovgjzGU7RUOLPCbsZBFAfmVND8rMV863RrcyVmjUI
          El5vviLHHMFQCuG11wxn9pWfhJGwcGPNkZSa+nZ/3ovFNDq8a6ODLapS7I2/qKRizM4Jj
          AOmQZoZbKh+NDbeNlBXg5b00fdxP6h6EWfONjOIhb5YRGDiYK1vHSJmCsp4PB8gkaTpNk
          zjz8qaFE0tyW/f9zCe5/GiKBatKJWpfZG/rIKdzhx4xNODo7J8Ckdg9tK3uZ66kW8za0d
          dUxugaAB/zlm1WjU0TffFVfY79ZCr/PZqAEbvCm7d7PNJU4Zimd5QPGnYL6lCvYVYB3Sk
          MkTF7zBn2f0BzVdTGsBBy2toNOH0qg8axLOCKINhDp3s5c0CiwIfgu+2I5LrGvcw5ZkdA
          Dtw4IDYOILmu0PKGK0CNqJ6B9L4FUONVKeaDRE8cZ0H4kK5FmFeACTRpjQ+bII5BJ5umr
          oxWFV3vcEAXEzFjVFt5ULJlMWUrx9BnTPd6ANmoxmER/sFxUgfFmnqtbXI8S+4vTgc+P6
          wF9Gsmu85cgLnh/5kiucknN92tNp7BsYFG3DjVy/ymfOH9bBNqd7yL+iZ4GqI0=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - Ar4P8ITJih5tTIz8py4bXivSYBOMTGWuoMxaMg7mc3Yxp5ktDF694tK/Rggw8gtTw/8k5
          ggYf/SMa+JXsOCGzcArhEqqug7SGdOr4m2MhdbSKyBUD+os77FfsmmH6TyfdSuBQJuvtN
          udvK8SiwsKaNjafhpPWdTVyMWwNipIolDIyiKMuO10UoM3OMPFqX76rrnQhSzVl+fAw98
          rta1G4Ypb7PVHlFyFbSq9eAsnCtpAeqSqbKcCV2CqeIlkyGK7snp+U8BJhSzYATKvVAgQ
          vrTcjUKcvk4djk2hJEr2bQ0Tb3sBwtEEStq7ri8VaBuWSf1nJD+NAwPGUINGQbwVAMy8Q
          r40YFyU8IYoMuHLZPPnZssbaOoLiboc818uCbI9+A536UZsjH+1qaVuEi+t9Z2oug3lTy
          cJm2VVJTvA2zCSLCELPij4vvsl7D/XiNqJP44QfoUqelNeB1wOIl1EEyCqLRjCrblYOiY
          y52PVLvmb/znVXcqe1miSnEab9je609GusQFrTJIZbRcOCkHYPx0yNglBqe5S/GWvETFV
          ViBCPuwADevjKN0NUBAIE6aaHRWiC7AG4oPZ0DLzV0toLZ9s9J+dXg1+P3ZtgCnMC9FzU
          514KtK8UQXX8fcsyf453pq4bmxG5ITNpnfurtC11KUve0gqjK7eVY7jUzmZUbI=
      DEPLOY_KEY_SBOM: !encrypted/pkcs1-oaep
        - oWmr0jv2BPoCWHAliiHu2XtawhC0xXiKFnjjoPzQT1IvWwBj0v6G8Bt3hjFOHZOxW4Tta
          u0fWYGdkqnJgt5sbwVXk6pUj+7TPqpazIszlx6/NxFYJV3ru0KMH15vHyJ2JmBJFNpqD3
          OGA34HYan5RKEEK/XCNsQal/ToQ34Z9hQa6N4zWOXh9noJMTOp53q45acouUdkgsdeRIX
          4GZhI+9LDq/syqAK/Hux4AVGM+UGHNvSXiIyct6wvrcj0V6y5fVeO9jRUecVC4hqsapvj
          59dNJCtQ99EzBuBCZJzqI7Pz56xPzhm86Y9oFbUZYOs6jpoeSIOQLcKKwG/W0sDG2EZzF
          2BRdZDVN5g/sky/9KTTtw/Cl8tsyfufLZ1BWDniuS6RASIdP8tM9wVkPeoEDvSgGxbDdA
          H8thsYO5u/IAC+cBNvaK7o6TrDlmsb0KZHER8tKIdiE1tECvEhVWQO8lSRwENswpvRMRp
          cVlIxMYFRJz5hOkICRd3PQNfB5xyW8PIEc29SVZjYqudlBDpwgigEGD3FG3o6l0ClzDNm
          NT9QHtFqLlSe2rB2TbfDIZc90/RUGptah8O8ecri/ZFsTpqc3qtiQXuf2Cf2m32/e1Mxx
          4qk2YOyC9FppQYhCv1UZJhCNpaFlDV5TpcPJ6DY/7fWTOOWK+wQ5wtnoGYIE64=
        - muoJEHt4rF4IvGksaJaobOm4d9qoR2J7xSb9pSPdVZt/6hPx48nqLkPsqC5IcDxF9jm1P
          folwAeDytpZa5TcvPVTVYqqYoIceVpQfXtIibEeUYoxcMICtOV63sho+Bta6CogUFyI3F
          0HUmS3FX8fJ41Xtc4gr3SzcEpEgsYTMlYCztWtNY+quAk771tkf+XV749y1YsSvhkPblC
          j7m0WeYDJ5Ob8k/FD6cVkSsSJ/m/9Fd8L3R/QrN/zRPWkvhCu04/smZAQLIs9SV6kmFxM
          8mr5dXRESw7oepSSAK9re2QHTd2lAYYTybnqrraRhhPJiVxWrKBdIWgpO7Yywq4AweWs/
          S9mo62kYV1b7hSUJs2SmjWAZPDB6NASymLGhPvTgiad1N5Uehgxl3i+08J9NNGqvTgk3W
          1XFI/ySzNa4PnoFYIW1RTyK60/uXhOl0t0saMRE7ZkMaa/+P7wXJGyUtfHDwxq/0aQUEq
          MEHloIAkoNI9UsxkXCSUQF3zuNl6CPoo7afXECcrWc/YODix2xgq2e6fh1n2RT25s02/Q
          MrVkvEni1lteQTI4JcH8vawyAxd6zykYPJE4gYtrC1gowBJTTV4i2D5QVhB8jcBuv9hCE
          CI06y1eWBXK3LS7SqbLlumDjkCTLEdW+Kx4jNlzck94zItvjcnJQuBfpu2TQcY=
        - VkdOHFifmbvta61nENRrc2Dr2bvonm9hYPz+943hygCC9InM90eBrHiEEWqSnajBze9d/
          q72+6yDWqEa48PRkCm9jYmL02t1OHUJjQTpFK/ITqJntELFh1p3LJbG8d0Iegg4Kqyhcv
          rYos0iTbfRkN45xr3nHtlIOvBQZ9rf1y9pbFqW1ilMdkq6paB5C77U2cXspgu/jMuSgo2
          0hPaf06yfxdw0j8O3WPs2f9HFDsvmki5BbY717AHDX/YWP4Vh5vSfJU7JDROC3FTSEuE6
          brmKCYEk59zFrFVJ2+6vKzSHzLZfdm7x4cT6ztCwugRbCILzf9YA/dljKP515Crh+ukBJ
          iIYsXun9IvKddrSsaTIqhxBNrixxA30DvW55TQSekRZWP+I4/kqKoCpa+GNIiD9dfOETs
          SVXyfm5MtVacV1bengMz6CuLPfs037KJo594JQpCQg4uPIEcPLgBqDNDS1HDD7kQ4B0/f
          aPj0YhVHw3M7mwPPBLEygof/jCI5LKKMv1AfBRp63RSHLSu6R2uq5GMPqI28spuXfTFGS
          ZnJJR+FTAux+r/n6vaIF2bsg5O+y+stsM1011IeNnDfjWtZoboz30sy09QkSERrHBrwH6
          CC2C3Sv4rDo8jmiHydl4kraNfSstBli4/rPUR4IV8t9cTPo8Arur55u2pmQFJo=
        - kCcNyD3wS1NsEPyvhhnyvyK+fvaR/eDhF4TmkN7Ef52xQ/h+rWUpSBnctU5ASJZdcmtza
          7LKiBz1QLxxfQHEEzQifRi0qM3OexstI0x4DlY3QwWPHwMnjln7EHojPoeR5lLzya7DNo
          LijR29RmuXIJ+GVkwWXa6NYpYsVaRHg5wTmvJQxClG0v4TMUjNN8PqE7spdAakvQYQnqC
          I2YbaNi0uWmV6TPR32TYc8GjDeQT4QMJ8c/3l0fjG8MuViTSYPOKTs1/zpZKm0eqVZXOC
          PQC/zmsWDkwkjKDTngVBObD/mNGim7XWGONC2Nq+qQEmR317DmQZ9jtIHgoURGLDOE9Wv
          CnD6jnlOW47xZGZvwLw6rQBdjH1FdZYigoL9KnV8npW8xMNPweY0t2gHUXAG8UxA1QJlJ
          Lv5HYviC/AkhJtmCCzVHuRwSN+yCAQNyQBw9eNNvdL1JtQb9uuP9v/rwnLBi/INrWXxYU
          nddrO4VeVgxAkEHwr/DedqBqkaaRAyf4frDXZD7QJhrqrAoXJHhXt7oSQjxgdpf8BIfTj
          WJumg1jlhZMWG55RP/dCdDuikp6Hmk5v4grPeRh2O7LfgpDFTNcbnNHcHp5dvdTJGSra2
          j3y5O9geqfQjjlyGYe4r1umigKpeBh+PkgOrzdaJf1W+278AoVGRIH7JxK80cI=
        - D0qPTx2FjyBwT6EU51gymQVfCfw3r4obCpZUmOHyFVOcD2sC+7hVoctek8u3XHwXkGOQO
          HK6e/lNXfKqDWTq8s9qX2Fn5o0DEaDRC9RxLE2lm47OiHbA+Ez8FLDKB2bWfqRb+YG+zz
          vA8Xn8biubIdHy2vYIUgWHNWpdxUAhvdYfKoyciWfxWmCipGNc/sq4UMPbIOPWKrn8K66
          IQpUItR7rf3S4wRPucQ3Xh1hatrZ1MOK4n7jDeCLrd5AUEQW+kxq3ykb8qriFPMUEDys+
          FmN8TTdCeaPe382i2kpiozPJ+BcsDKFDctLrBnEveV27c9SsU2xwNUQT4vYkNBiFK0AWB
          v2isyPKEKIfWAJyTa9z+g2lYE7kkXOqyuwadSSla23u9s020yor/iNmi+Df62sAZJ2qAF
          89EcQ6TjvFTg3zT1/xaxpy/H4k5JIV8TyCeYQH+UjZczr1OqZEKYIAAk4KYesNr3DNt3L
          XISCFnVkIH0bYKX0SvqPUT6WR/osvajYF9UZR4eR5wFXkzIKtvgHuRe9iORE2fjr1t9zW
          Ek7RrrXFNNJ6HzLJsWwSghZQAm0sfD3s5GF0pmM6tiUpiSJWjAnfzvAOa0XRJJSO6oy9n
          pLwU5C01zP/2A1ZsnCI7qRLy4EZ1B8NAgGKEBgsYvk5o6NKYdf5hWY2dj3fsbE=
        - ASfPpApPoU4BldQOOlKiSkJIO98+kLtpU94JrJp2s5IFvRroKZTg/1vblgo933R+6gzfT
          qlytNs26bNb6GTfj/orQQ1BBU2TmCDFkrOr87BXU/RUHuabAFpJ4MhgpxdDIt4oyQbGFP
          mU11UGQ43ys/iTOchemhN4o7DsuU31PgcJ6bWqIqyzBSRI6cR52Y2vMhppUm74ffPcxLL
          tN90oqICk4uI9XHTfW3bpds5aWCYqE3Rw/O0xlqJJZHzlMPn4NthUKaGyGgXM3dso649b
          6BgAhxhjWSubMHbjULGMIRPLWWu6N/wslm76tmfb6c0dt/0IGYF4UzuwgAnI1lgOSNg9b
          DMembd1Y+jRL1JsTNobhnG/f49n8EqcNjlrgUCsg7nEmi2xUByAIG7SlHlq+/ttPh6n7w
          5NrXqKbZrljJ3XqA6solMNqAly1fsR4HQV7DowxHexFrV4+V6kcg35Ggj77jKot0pk0om
          sSo/vM2z8CGJt3dsDIg1bHOYDe0nTTMCQBEiaikr+/fueRWWng8wHBKILFm9mGpMQJ28B
          vVm+0nGAwoy/7G5tgLUnIZOoYmmNOJIblBuqbBXMaL1OUAZ+nQbcfr+f6FEFm/yonGWrq
          RwuErxyB0erVvm076vn7Dx8NT9T58s08hNS0HFLG7aOpwV2nHECCHYDWO0yWXI=

- semaphore:
    name: semaphore-container-images-kolla-push-antelope
    max: 1

- semaphore:
    name: semaphore-container-images-kolla-push-bobcat
    max: 1

- semaphore:
    name: semaphore-container-images-kolla-push-caracal
    max: 1

- semaphore:
    name: semaphore-container-images-kolla-push-caracal-aarch64
    max: 1

- job:
    name: container-images-kolla-build
    nodeset: ubuntu-jammy-large
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 10800
    vars:
      docker_namespace: kolla
      docker_registry: osism.harbor.regio.digital

- job:
    name: container-images-kolla-build-aarch64
    nodeset: ubuntu-jammy-large
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 10800
    vars:
      base_arch: aarch64
      docker_namespace: kolla/aarch64
      docker_registry: osism.harbor.regio.digital

- job:
    name: container-images-kolla-build-antelope
    parent: container-images-kolla-build
    vars:
      version_openstack: "2023.1"
      push_images: false

- job:
    name: container-images-kolla-build-bobcat
    parent: container-images-kolla-build
    vars:
      version_openstack: "2023.2"
      push_images: false

- job:
    name: container-images-kolla-build-caracal
    parent: container-images-kolla-build
    vars:
      version_openstack: "2024.1"
      push_images: false

- job:
    name: container-images-kolla-build-caracal-aarch64
    parent: container-images-kolla-build-aarch64
    vars:
      version_openstack: "2024.1"
      push_images: false

- job:
    name: container-images-kolla-push-antelope
    parent: container-images-kolla-build
    semaphores:
      - name: semaphore-container-images-kolla-push-antelope
    vars:
      version_openstack: "2023.1"
      push_images: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGES_KOLLA
        pass-to-parent: true

- job:
    name: container-images-kolla-push-bobcat
    parent: container-images-kolla-build
    semaphores:
      - name: semaphore-container-images-kolla-push-bobcat
    vars:
      version_openstack: "2023.2"
      push_images: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGES_KOLLA
        pass-to-parent: true

- job:
    name: container-images-kolla-push-caracal
    parent: container-images-kolla-build
    semaphores:
      - name: semaphore-container-images-kolla-push-caracal
    vars:
      version_openstack: "2024.1"
      push_images: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGES_KOLLA
        pass-to-parent: true

- job:
    name: container-images-kolla-push-caracal-aarch64
    parent: container-images-kolla-build-aarch64
    semaphores:
      - name: semaphore-container-images-kolla-push-caracal-aarch64
    vars:
      version_openstack: "2024.1"
      push_images: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGES_KOLLA
        pass-to-parent: true

- job:
    name: container-images-kolla-release
    parent: container-images-kolla-build
    vars:
      is_release: true
      push_images: true
    secrets:
      - name: secret
        secret: SECRET_CONTAINER_IMAGES_KOLLA
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - flake8
        - python-black
        - yamllint
    label:
      jobs:
        - container-images-kolla-build-antelope
        - container-images-kolla-build-bobcat
        - container-images-kolla-build-caracal
        - container-images-kolla-build-caracal-aarch64
    gate:
      jobs:
        - flake8
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - flake8
        - python-black
        - yamllint
    periodic-midnight:
      jobs:
        - container-images-kolla-push-antelope
        - container-images-kolla-push-bobcat
        - container-images-kolla-push-caracal
        - container-images-kolla-push-caracal-aarch64
    post:
      jobs:
        - container-images-kolla-push-antelope:
            branches: main
        - container-images-kolla-push-bobcat:
            branches: main
        - container-images-kolla-push-caracal:
            branches: main
        - container-images-kolla-push-caracal-aarch64:
            branches: main
    tag:
      jobs:
        - container-images-kolla-release
